JENKINS_URL: 'SETME'
JENKINS_USER: 'SETME'
JENKINS_USER_TOKEN: 'SETME'
JENKINS_JOB_TOKEN: "SETME"
MONGO_DB_HOST: 'localhost'
MONGO_DB_PORT: 27017
MONGO_DB_NAME: 'dxmanager'
PORT: 5001
DEBUG: True
TEST: False
