push:
    - match:
        owner: "dataxu"
        branch: "master"
        no_message: '^\[auto\].*$'
      trigger:
        job: "{repo}_master"

    - match:
        owner: "dataxu"
        branch: "dev-.*"
      trigger:
        job: "{repo}_dev-feature"
        params:
            branch: "{branch}"

    - match:
        owner: dataxu
        branch: "rel-.*"
        created: true
      trigger:
        job: "{repo}_rel"
        params:
            branch: "{branch}"

    - match:
        owner: dataxu
        repo: "edge|streaming"
        branch: "master-aws|rel-aws|rel-ec2-master"
      trigger:
        job: "{repo}_master-aws"
        params:
          branch: "{branch}"

pr:
    - match:
        repo: ".*"
        owner: ".*"
        branch: ".*"
        actions:
          - opened
          - synchronize
      trigger:
        job: "{repo}_pr"
        params:
            fork: "{owner}"
            branch: "{branch}"
            pr_number: "{pr_number}"

issue:
    - match:
        repo: "dxng"
        owner: "dataxu"
        message: "(add|remove|replace)[ _-]label.*"
        actions:
          - created
      trigger:
        job: "github_comment-to-label"
        params:
            repo: "{repo}"
            comment: "{comment}"
            issue_number: "{issue_number}"
    - match:
        repo: "dxng"
        owner: "dataxu"
        message: ".*:shipit:.*|.*:sheep:.*|.*:ship:.*|.*:shell:.*|.*:shaved_ice:.*"
        actions:
          - created
      trigger:
        job: "tools_merge-pr"
        params:
            repo: "{repo}"
            pr_number: "{issue_number}"
